"""phase 3: knowledge system, email classification, rag traces, approval states

Revision ID: e1b60a1b1bd3
Revises: 24c935fc4272
Create Date: 2026-07-25 13:13:12.880756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1b60a1b1bd3'
down_revision: Union[str, None] = '24c935fc4272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres ENUM value additions aren't detected by autogenerate and can't run
    # inside the same transaction as a statement that uses the new value — safe
    # to run here since nothing in this migration inserts 'mock' rows.
    # SQLAlchemy's Enum type stores the Python enum *member name* ('MOCK') in
    # Postgres by default, not `.value` ('mock') — matches how 'GMAIL' (not
    # 'gmail') was already stored for these same two columns.
    op.execute("ALTER TYPE email_provider ADD VALUE IF NOT EXISTS 'MOCK'")
    op.execute("ALTER TYPE integration_provider ADD VALUE IF NOT EXISTS 'MOCK'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_query_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insufficient_evidence', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_injection_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_query_traces_organization_id'), 'rag_query_traces', ['organization_id'], unique=False)
    op.create_table('email_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('SALES', 'SUPPORT', 'COMPLAINT', 'BILLING', 'PROJECT', 'MEETING', 'INTERNAL', 'NEWSLETTER', 'SPAM', 'OTHER', name='email_category'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='email_priority'), nullable=False),
    sa.Column('urgency', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='email_priority'), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='email_sentiment'), nullable=False),
    sa.Column('requires_reply', sa.Boolean(), nullable=False),
    sa.Column('contains_lead', sa.Boolean(), nullable=False),
    sa.Column('contains_task', sa.Boolean(), nullable=False),
    sa.Column('contains_deadline', sa.Boolean(), nullable=False),
    sa.Column('contains_payment_issue', sa.Boolean(), nullable=False),
    sa.Column('possible_spam', sa.Boolean(), nullable=False),
    sa.Column('possible_prompt_injection', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('raw_model_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', name='uq_email_classification_message')
    )
    op.create_index(op.f('ix_email_classifications_message_id'), 'email_classifications', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_classifications_organization_id'), 'email_classifications', ['organization_id'], unique=False)
    op.add_column('approval_requests', sa.Column('resolved_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('approval_requests', sa.Column('simulated_send_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column(
        'daily_reports',
        sa.Column(
            'metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
    )
    op.add_column(
        'daily_reports', sa.Column('narrative', sa.Text(), nullable=False, server_default='')
    )
    op.add_column(
        'document_chunks', sa.Column('token_estimate', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'document_chunks',
        sa.Column(
            'metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
    )
    op.add_column('documents', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('original_filename', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('safe_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('documents', sa.Column('checksum', sa.String(length=64), nullable=False))
    # add_column (unlike create_table) does not auto-create a referenced Postgres
    # ENUM type — must be created explicitly first.
    document_processing_status = sa.Enum(
        'UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'ARCHIVED', name='document_processing_status'
    )
    document_processing_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'documents',
        sa.Column(
            'processing_status',
            sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'ARCHIVED', name='document_processing_status'),
            nullable=False,
            server_default='UPLOADED',
        ),
    )
    op.add_column('documents', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_unique_constraint('uq_document_org_checksum', 'documents', ['organization_id', 'checksum'])
    op.create_foreign_key('fk_documents_uploaded_by_users', 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.add_column('leads', sa.Column('source_message_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('requested_service', sa.String(length=500), nullable=True))
    op.add_column('leads', sa.Column('budget', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('deadline', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('confidence', sa.Float(), nullable=True))
    op.create_foreign_key('fk_leads_source_message_id_email_messages', 'leads', 'email_messages', ['source_message_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('source_message_id', sa.UUID(), nullable=True))
    task_priority = sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='task_priority')
    task_priority.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'tasks',
        sa.Column(
            'priority',
            task_priority,
            nullable=False,
            server_default='NORMAL',
        ),
    )
    op.add_column('tasks', sa.Column('confidence', sa.Float(), nullable=True))
    op.create_foreign_key('fk_tasks_source_message_id_email_messages', 'tasks', 'email_messages', ['source_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_source_message_id_email_messages', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'confidence')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'source_message_id')
    op.drop_constraint('fk_leads_source_message_id_email_messages', 'leads', type_='foreignkey')
    op.drop_column('leads', 'confidence')
    op.drop_column('leads', 'deadline')
    op.drop_column('leads', 'budget')
    op.drop_column('leads', 'requested_service')
    op.drop_column('leads', 'source_message_id')
    op.drop_constraint('fk_documents_uploaded_by_users', 'documents', type_='foreignkey')
    op.drop_constraint('uq_document_org_checksum', 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_column('documents', 'archived_at')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'checksum')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'safe_filename')
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('document_chunks', 'metadata')
    op.drop_column('document_chunks', 'token_estimate')
    op.drop_column('daily_reports', 'narrative')
    op.drop_column('daily_reports', 'metrics')
    op.drop_column('approval_requests', 'simulated_send_result')
    op.drop_column('approval_requests', 'resolved_payload')
    op.drop_index(op.f('ix_email_classifications_organization_id'), table_name='email_classifications')
    op.drop_index(op.f('ix_email_classifications_message_id'), table_name='email_classifications')
    op.drop_table('email_classifications')
    op.drop_index(op.f('ix_rag_query_traces_organization_id'), table_name='rag_query_traces')
    op.drop_table('rag_query_traces')
    # ### end Alembic commands ###
    # See 676a7ecf4d33: Postgres ENUM types outlive their table/column and must
    # be dropped explicitly, or a later upgrade() fails with "type already exists".
    for enum_name in ("task_priority", "document_processing_status", "email_sentiment", "email_priority", "email_category"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # Note: 'mock' added to email_provider/integration_provider above is NOT
    # reverted here — Postgres doesn't support removing a single enum value
    # (ALTER TYPE ... DROP VALUE isn't implemented). Those two enum types
    # predate this migration and are dropped/recreated by 24c935fc4272's own
    # downgrade, which will simply recreate them without 'mock' — acceptable
    # for a dev-only forward-leaning migration history.
